# -*- coding: utf-8 -*-
"""10. Retrieve words from the hashtags files

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hIu-vTnzlrHZnQItey_HOKtW-pR8Y-l_
"""

from pyspark.sql import SparkSession
spark = SparkSession.builder.appName('Hashtags from words').getOrCreate()

"""Given a text file, with the german words and their meaning. Read that into a dataframe and write that in a parquet file.


"""

class Solution:
  def __init__(self):
    self.path = '/content/hashtags.txt'

  def readcsv(self):
    df = spark.read.text(self.path)
    return df

  def interpret(self, df):
    from pyspark.sql.functions import split, explode, col

    df = df.withColumn('array', split(df.value, '#'))
    df = df.withColumn('hashtag', explode(df.array))
    df = df.drop('array')
    df = df.drop('value')
    return df

Ind_obj = Solution()
df = Ind_obj.readcsv()
df = Ind_obj.interpret(df)
df.show()