# -*- coding: utf-8 -*-
"""13. Finding the most obscure Marvel names/graph set

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16SVkoZESWzqWUuhjWu56yzjFbBUzAHPc
"""

from pyspark.sql import SparkSession
spark = SparkSession.builder.appName('most-obscure').getOrCreate()

from pyspark.sql import functions as func
from pyspark.sql.types import StructType, StructField, StringType, IntegerType, LongType

schema = StructType([ \
                     StructField("ID", IntegerType(), True), \
                     StructField("name", StringType(), True)])
names = spark.read.schema(schema).option("sep", " ").csv('/content/Marvel+Names')
lines = spark.read.text("/content/Marvel+Graph")

connections = lines.withColumn("ID", func.split(func.col("value"), " ")[0]) \
    .withColumn("connections", func.size(func.split(func.col("value"), " ")) - 1) \
    .groupBy("ID").agg(func.sum("connections").alias("connections"))

# Finding the minimum connections

minConnectionCount = connections.agg(func.min("connections")).first()[0]
minConnections = connections.filter(func.col("connections")==minConnectionCount)
minConnectionsWithNames = minConnections.join(names, "ID")
minConnectionsWithNames.show()