# -*- coding: utf-8 -*-
"""5. Find Average Number of friends for each age

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hIu-vTnzlrHZnQItey_HOKtW-pR8Y-l_
"""

from pyspark.sql import SparkSession
spark = SparkSession.builder.appName('Age-Average').getOrCreate()

"""- Average Number of friends for each age - input : csv file, output - dataframe"""

class Solution:
  def __init__(self):
    self.path = '/content/fakefriends-header.csv'

  def readcsv(self):
    df = spark.read.option('header', True).option('inferschema', True).csv(self.path)
    return df

  def find_average(self, df):
    from pyspark.sql.functions import col, avg, round
    df = df.groupBy(col('age')).agg(round(avg(col('friends')),2).alias('average_friends')).sort(col('age'))
    return df

Ind_obj = Solution()
df = Ind_obj.readcsv()
df = Ind_obj.find_average(df)
df.show()