# -*- coding: utf-8 -*-
"""8. Total Amount spent by customers

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hIu-vTnzlrHZnQItey_HOKtW-pR8Y-l_
"""

from pyspark.sql import SparkSession
spark = SparkSession.builder.appName('df-amount-spent').getOrCreate()

"""- Minimum temperature



"""

class Solution:
  def __init__(self):
    self.path = '/content/customer-orders.csv'

  def readcsv(self):
    df = spark.read.option('inferschema', True).csv(self.path)
    return df

  def rename(self, df):
    df = df.withColumnRenamed('_c0', 'customer_id')
    df = df.withColumnRenamed('_c1', 'item_id')
    df = df.withColumnRenamed('_c2', 'amount_spent')
    return df

  def sumbycustomerid(self, df):
    from pyspark.sql.functions import round, sum, col
    df = df.groupBy('customer_id').agg(round(sum('amount_spent'), 2).alias('total_sum'))
    return df

Ind_obj = Solution()
df = Ind_obj.readcsv()
df = Ind_obj.rename(df)
df = Ind_obj.sumbycustomerid(df)
df.show()