# -*- coding: utf-8 -*-
"""9. Dictionary words text to parquet

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hIu-vTnzlrHZnQItey_HOKtW-pR8Y-l_
"""

from pyspark.sql import SparkSession
spark = SparkSession.builder.appName('Dictionary words').getOrCreate()

"""Given a text file, with the german words and their meaning. Read that into a dataframe and write that in a parquet file.


"""

class Solution:
  def __init__(self):
    self.path = '/content/german text.txt'

  def readcsv(self):
    df = spark.read.text(self.path)
    return df

  def interpret(self, df):
    from pyspark.sql.functions import split, explode, col, regexp_replace

    df = df.withColumn('array', split(df.value, '\t'))
    df = df.withColumn('array3', split(df.array.getItem(1), '\d+'))
    df = df.withColumn('array2', split(df.array.getItem(0), '\d+'))
    df = df.select(col('array2').getItem(1).alias('german_word'), col('array3').getItem(0).alias('english_word'))
    df = df.withColumn(
    'cleaned_word',
    regexp_replace(col('german_word'), r'^\s*\.\s*', '')
    )
    df = df.drop(col('german_word'))
    return df

  def writetoparquet(self, df):
    df.write.parquet('german_words.parquet').path('/content/')

Ind_obj = Solution()
df = Ind_obj.readcsv()
df = Ind_obj.interpret(df)
Ind_obj.writetoparquet(df)
df.show()